spring:
  output:
    ansi:
      enabled: always
  application:
    name: development application
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
            view: DEBUG
            mvc:
              method:
                annotation: DEBUG